version: '3.5'

services:
  django:
    build: ./app
    expose:
      - "8000"
    networks:
      - django
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    volumes:
      - static:/app/static
    depends_on:
      - postgres
    ports:
      - "8001:8000"

  postgres:
    build: ./db
    expose:
      - ${DB_PORT}
    networks:
      - postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data/

  sqlite_to_postgres:
    build: ./sqlite_to_postgres
    networks:
      - sqlite_to_postgres
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    depends_on:
      - django

  elastic:
    image: elasticsearch:7.17.6
    expose:
      - "9200"
    networks:
      - elastic
    environment:
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - discovery.type=single-node
    depends_on:
      - django
    ports:
      - "9200:9200"
  etl:
    build: ./etl
    networks:
      - etl
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - ES_HOST=http://elastic:9200
    depends_on:
      - elastic

volumes:
  pgdata:
  static:

networks:
  django:
    name: movies_net
  postgres:
    name: movies_net
  sqlite_to_postgres:
    name: movies_net
  elastic:
    name: movies_net
  etl:
    name: movies_net



